### ISSUE TITLE
Cannot install straightedge-cli

### ISSUE THREAD

**Issue by chrishobcroft** [heystraightedge/straightedge-cli#1]
I am trying to install straightedge-cli on Ubuntu 18.04.3 LTS using instructions here: https://github.com/heystraightedge/straightedge-cli/blob/master/README.md

Here's what I do:

1. Check I have the "Requires"

```
straightedge-0@chrishobcroft-straightedge-0:~$ tsc --version
Version 3.6.3
straightedge-0@chrishobcroft-straightedge-0:~$ node --version
v12.10.0
```

2. Clone the git repo:

```
straightedge-0@chrishobcroft-straightedge-0:~$ git clone https://github.com/heystraightedge/straightedge-cli.git
Cloning into 'straightedge-cli'...
remote: Enumerating objects: 803, done.
remote: Total 803 (delta 0), reused 0 (delta 0), pack-reused 803
Receiving objects: 100% (803/803), 593.20 KiB | 1.58 MiB/s, done.
Resolving deltas: 100% (515/515), done.
```

3. Install 6 of the 7 dependencies specified in [the straightedge-cli npmjs page](https://www.npmjs.com/package/straightedge-cli) - _running the commands inside the cloned repo_:
- `npm i @polkadot/api`
- `npm i @polkadot/keyring`
- `npm i @types/filesystem`
- `npm i commander`
- `npm i dotenv`
- `npm i ts-node`
- `npm i straightedge-node-types`

4. Run `tsc` inside `~/straightedge-cli`, get these errors:

```
straightedge-0@chrishobcroft-straightedge-0:~/straightedge-cli$ tsc
src/index.ts:13:31 - error TS2307: Cannot find module 'straightedge-node-types/dist/identity'.

13 import { IdentityTypes } from 'straightedge-node-types/dist/identity';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:14:29 - error TS2307: Cannot find module 'straightedge-node-types/dist/voting'.

14 import { VotingTypes } from 'straightedge-node-types/dist/voting';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:15:32 - error TS2307: Cannot find module 'straightedge-node-types/dist/signaling'.

15 import { SignalingTypes } from 'straightedge-node-types/dist/signaling';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 3 errors.
```

**Comment by bneiluj** [comment]
There is an NPM package to make thing easier to install`straightedge-cli`. 

Run `npm i edgeware-cli -g` (Make sure you have auth `sudo` and install as a global package)
To run straightedge-cli, run: `edge` and `edge --help`
